### PR TITLE
remove unused variable simple_pdg

### PR DESCRIPTION
**Pull request by lgarren**
This PR can be used to investigate problems found when building with clang.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
Oh, these CI tests did not include larsimrad. :(

**Comment by gartung** [comment]
I think @vitodb  needs to update something in the CI scripts.

**Comment by lgarren** [comment]
Contacting him now.  This repository should not automatically be included yet.

**Comment by lgarren** [comment]
trigger build with pull request LArSoft/larsimrad#1

**Comment by plasorak** [comment]
Hi Lynn,
I've fixed the clang errors here:
https://github.com/plasorak/larsimrad/tree/plasorak/mismatched-tags
It's slightly hacky but I don't see how else to do it. I'll create a pull request on bxdecay0 so that we can have it for the next version.

**Comment by plasorak** [comment]
I got it to compile with the build tags: e19:prof and c2:prof.

**Comment by plasorak** [comment]
Did you build bxdecay0 with clang? I get a lot of errors.

**Comment by lgarren** [comment]
@plasorak Thank you
bxdecay0 is available for e19 and c7, but not for c2.  Would you create a PR for larsimrad with your changes?

**Comment by plasorak** [comment]
Sorry I actually meant c7. Ok, I'll go ahead with the PR.

**Comment by lgarren** [comment]
approve

**Pull request merged**
